import random

def generate_island():
    scenes = [
        "You discover a fog-covered island with strange glowing mushrooms.",
        "You land on a beach of black sand where parrots mimic your voice.",
        "A volcano rumbles in the distance. You hear drums in the jungle.",
        "You find a crashed airship wrapped in jungle vines.",
        "Giant crabs fight over treasure on a sunken temple shore.",
        "The island is frozen, and mysterious footprints lead inland.",
        "A storm brews over an island covered in twisted shipwrecks.",
        "You find a lighthouse still lit, but no one is inside.",
        "The beach is littered with golden coins and empty armor.",
        "You stumble upon a grove of whispering trees.",
        "An obsidian monolith stands in the middle of a desert island.",
        "A village of friendly otter-folk offers you a drink.",
        "You hear chanting from deep within a vine-covered ruin.",
        "You discover a waterfall that flows upward.",
        "The entire island is floating slightly above the sea.",
        "You encounter a talking turtle who offers cryptic advice.",
        "A ship-shaped building sits in the middle of the island.",
        "Strange glowing eyes watch you from the trees.",
        "You find a library in perfect condition, guarded by stone lions.",
        "A geyser erupts nearby, revealing glimmering gemstones.",
        "A sleeping giant lies half-buried in the sand.",
        "The sand feels like glass and hums beneath your feet.",
        "You find a garden of singing flowers.",
        "An enormous anchor is embedded in the center of the island.",
        "You discover an altar with offerings of pearls and coral.",
        "You find a dried-up riverbed full of bones.",
        "A rainbow arcs perpetually across the island.",
        "You encounter a hermit crab the size of a wagon.",
        "The palm trees move ever so slightly when you’re not looking.",
        "A group of mischievous monkeys steal your map.",
        "You find a broken bridge made of dragon bones.",
        "The entire island smells strongly of cinnamon.",
        "The sand glitters like stardust beneath the moon.",
        "You discover a pit filled with ancient pirate flags.",
        "You find a journal half-buried with the final entry: 'Run.'",
        "You are followed by a shadow that doesn’t belong to you.",
        "A crystal cavern hums with magical energy.",
        "There is a perfectly square stone tower, untouched by time.",
        "You find an abandoned harbor with phantom ships.",
        "You hear flute music but see no one.",
        "A wild boar with a golden tusk charges from the trees.",
        "You uncover a map carved into coral.",
        "You find a conch shell that speaks when held to your ear.",
        "A strange fog causes time to flow backwards.",
        "An enchanted boat offers you a ride inland.",
        "You meet a fisherman who claims he's been here 200 years.",
        "A chessboard of stone lies in the jungle, mid-game.",
        "The trees shift positions when you look away.",
        "You are greeted by parrots who know your name.",
        "You find a pond reflecting a sky from another world.",
        "A siren’s song tempts you toward jagged cliffs.",
        "You find a cave painted with stars and ancient tales.",
        "You walk in circles and return to your boat repeatedly.",
        "A sandstorm suddenly engulfs the island.",
        "You meet a child who insists you’re their long-lost parent.",
        "A serpent coils around the island’s tallest peak.",
        "You stumble into a pirate court in session.",
        "The waves around the island crash in perfect rhythm.",
        "You discover a massive golden bell, half-buried in sand.",
        "The tide reveals an underwater palace of glass.",
        "You meet an old woman weaving nets of moonlight.",
        "A storm never stops circling the island’s edge.",
        "You find an orchard of perfectly ripe fruit — too perfect.",
        "The jungle is filled with glowing insects that spell words.",
        "A golden bridge appears only at sunset.",
        "You find your name carved into a rock dated centuries ago.",
        "You hear your own voice calling from inside a cavern.",
        "You find a pirate ship fused with the island rock.",
        "A narrow tunnel leads to a glowing underground lake.",
        "The trees chant in unison during the full moon.",
        "You discover a ship locked in a block of ice.",
        "The clouds above mimic your every movement.",
        "You find a campfire still warm — but no one is there.",
        "A marble staircase spirals into the sky.",
        "You meet a ghost who asks for help finishing a journey.",
        "The stars above don’t match any known constellation.",
        "You find ancient coins falling from the sky like rain.",
        "A ship's figurehead warns you not to stay long.",
        "A tree shaped like a kraken watches over the bay.",
        "You find an ancient anchor made of bone.",
        "You hear a baby crying from deep in the jungle.",
        "You uncover a glowing egg in a nest of metal feathers.",
        "A sandbar leads to a second, smaller island.",
        "You find a pirate hat on a skeleton sitting on a throne.",
        "A magical mirror reflects a different island behind you.",
        "You find footprints that start at the water but lead nowhere.",
        "The island is covered in sleeping animals.",
        "A crow drops a gold ring at your feet.",
        "You stumble on a war between ants and termites.",
        "You find a spyglass that shows the future.",
        "The waves whisper secrets in ancient tongues.",
        "You discover a game board with moving stone pieces.",
        "The ocean glows neon near the shore.",
        "A single tree stands in the center, filled with clocks.",
        "You find a well that grants a single question answered.",
        "The cave walls echo back lies instead of sounds.",
        "You find a recipe book nailed to a stone with seaweed ink.",
        "An island goat charges at shadows only it can see.",
        "A door stands upright in the middle of the beach.",
        "You uncover a musical puzzle made of shells and driftwood.",
        "A lantern floats endlessly around the island.",
        "You find a monument made of melted swords.",
        "You see your reflection behaving differently.",
        "The moon seems closer here… too close.",
        "You find a message in a bottle: 'Don’t trust the birds.'"
    ]
    return random.choice(scenes)
